
common: &common
      app: usda_api 
      repository: "git@github.com:getlunchtray/usda_api.git"
      shared_paths:
            - 'config/database.yml'
            - 'config/app_config.yml'
            - 'log'
            - 'config/secrets.yml'
            - 'public/system'
production:
      <<: *common
      domain: 104.131.29.227
      user: sitedeploy 
      branch: master 
