# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d26ef6844511c8da5a3621b9245c2a06c0c3a0b9de5600821082d083c21a682772bcae1c40ececb589c0446255081b6bc0951e19b3c614cdb5d41d7f844bf498

test:
  secret_key_base: 630d5c522f91b08a8d89b927910619701852c56082ee7d4003a917af51769700d66cf0ffa17cb7ca14bb143d7d108850870f6fd018cfdc6c9f2e0877821632f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
